[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
provenance_chain = "BvkDzStztdtVZZXL5R364xwWNn3TfKG5xkN54KAV8giv"

[programs.localnet]
provenance_chain = "BchWFiSaRvWfyh5fYopg2XXVxaRtwBuUwyq65Mbu3svm"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"

[hooks]
